// https://mall.bilibili.com/mall/noah/search/category/v2

const body = {
    "keyword": "",
    "filters": "",
    "priceFlow": "",
    "priceCeil": "",
    "sortType": "pubtime",
    "sortOrder": "",
    "pageIndex": 1,
    "userId": "",
    "state": "",
    "scene": "",
    "termQueries": [
        {
            "field": "category",
            "values": [
                "2_175"
            ]
        }
    ],
    "rangeQueries": [],
    "extra": []
}

const res = {
    "code": 0,
    "message": "success",
    "errtag": 0,
    "data": {
        "pageNum": 8,
        "pageSize": 10,
        "numResults": 75,
        "pageTitle": "景品",
        "pageIndex": 1,
        "lastPage": 8,
        "firstPage": 1,
        "hasPreviousPage": true,
        "soldOutNum": 0,
        "cardActive": true,
        "card": {
            "isSubscribed": 0,
            "id": "0_3000003",
            "hotPower": 971718955,
            "ipId": 3000003,
            "subscribedNum": 1279772,
            "type": "ip",
            "logo": "",
            "banner": "//i0.hdslb.com/bfs/mall/mall/3b/50/3b50389d457828496f7f6048666884c4.png",
            "cover": "",
            "title": "VOCALOID",
            "zhTitle": "VOCALOID",
            "alias": "",
            "desc": "",
            "rank_score": 0,
            "itemsNum": 0,
            "jumpUrl": ""
        },
        "banner": null,
        "hasNextPage": true,
        "redirectUrl": "",
        "list": [
            {
                "itemsId": 12305717,
                "bizType": "hyg",
                "itemsType": 1,
                "name": "BANPRESTO GUNDAM 45th×HATSUNE MIKU VOCALOID 高达45周年初音未来 扎古谷努咪 景品手办",
                "price": "129",
                "itemsImg": "https://i0.hdslb.com/bfs/kfptfe/floor/3da7a1b88e7dad53aeded3c1a0e587cacfd6aaf9.png",
                "actMaterial": {
                    "cardBgImg": "",
                    "rightIconImg": "//i0.hdslb.com/bfs/mall/mall/54/72/547257984e503749b98f9751b4af7276.png"
                },
                "selfSold": true,
                "tag": "0_7",
                "marketingTag": "",
                "recommendTag": "",
                "soldOut": "0",
                "like": 5154,
                "brief": "",
                "properties": "",
                "preDepositPrice": "0",
                "maxPreDepositPrice": "0",
                "saleType": 0,
                "payType": 0,
                "coin": "",
                "pricePrefix": "",
                "priceSymbol": "¥",
                "priceDesc": [
                    "129"
                ],
                "extraInfo": "{\"TrackId\":\"pbaes.JdyPQyFqiZnSNPqm3nAj2rLMxWdTXTJyHn3x7MptPdluSFNFBD3rRtf_zMVXzK6zyIEvoPEPFC8denGOqgoF3ZaqWaTrT_ixAjDAmyjAZy-mRef3veQWpvejhA6u70I3WkXrFSIidreMNfYEN8h3j1uGZLJ7inttoTegLF6iASY\"}",
                "ipRightName": "",
                "ipRightId": 0,
                "brandName": "",
                "brandId": 0,
                "presaleDeliveryTimeStr": null,
                "preSale": null,
                "remain": null,
                "presaleStartOrderTime": null,
                "tags": {
                    "promotionTagV2": null,
                    "promotionTagNames": null,
                    "marketingTagNames": [
                        "欧气宝箱",
                        "满额权益"
                    ],
                    "saleTypeTagNames": [],
                    "typeAndLimitTagName": "余量预售",
                    "itemTagNames": [],
                    "recommendTagNames": null,
                    "attributeTagNames": [],
                    "rankAndSellPointTagNames": null,
                    "blindBoxHideTypeNames": null,
                    "titleTagNames": [
                        "余量预售"
                    ],
                    "ticketTag": null,
                    "starBoxSalePoints": [
                        "中国大陆独家"
                    ],
                    "exclusiveSalePoints": [
                        "//i0.hdslb.com/bfs/mall/mall/29/d3/29d32051b56e06a7307bddc88102ac69.png"
                    ],
                    "otherSalePoints": [],
                    "serviceTagNames": [],
                    "tagsSort": [
                        "adTagNames",
                        "promotionTagV2",
                        "promotionTagNames",
                        "marketingTagNames",
                        "serviceRightsTags",
                        "recommendTagNames",
                        "otherSalePoints",
                        "saleTypeTagNames",
                        "attributeTagNames",
                        "serviceTagNames"
                    ],
                    "adTagNames": [
                        "自营"
                    ],
                    "serviceRightsTags": []
                },
                "feedTag": {
                    "frontTag": [
                        {
                            "tagType": 1,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "余量预售",
                            "cornerRadius": 0,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "",
                            "backDayColor2": "",
                            "backNightColor1": "",
                            "backNightColor2": "",
                            "titleDayColor1": "ff18191C",
                            "titleDayColor2": "ff18191C",
                            "titleNightColor1": "ffE7E9EB",
                            "titleNightColor2": "ffE7E9EB",
                            "location": "front"
                        }
                    ],
                    "underTag": [
                        {
                            "tagType": 3,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "自营",
                            "cornerRadius": 4,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "ffFF6699",
                            "backDayColor2": "ffFF6699",
                            "backNightColor1": "ffD44E7D",
                            "backNightColor2": "ffD44E7D",
                            "titleDayColor1": "ffFFFFFF",
                            "titleDayColor2": "ffFFFFFF",
                            "titleNightColor1": "ffFFFFFF",
                            "titleNightColor2": "ffFFFFFF",
                            "location": "under"
                        },
                        {
                            "tagType": 3,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "满额权益",
                            "cornerRadius": 4,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "b3FFECF1",
                            "backDayColor2": "b3FFECF1",
                            "backNightColor1": "ff2F1A22",
                            "backNightColor2": "ff2F1A22",
                            "titleDayColor1": "ffFF6699",
                            "titleDayColor2": "ffFF6699",
                            "titleNightColor1": "ffD44E7D",
                            "titleNightColor2": "ffD44E7D",
                            "location": "under"
                        },
                        {
                            "tagType": 3,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "独家",
                            "cornerRadius": 4,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "1a8D9CF9",
                            "backDayColor2": "1aAF60FF",
                            "backNightColor1": "218D9CF9",
                            "backNightColor2": "21AF60FF",
                            "titleDayColor1": "ff9296FB",
                            "titleDayColor2": "ffAE65FF",
                            "titleNightColor1": "ff777AC8",
                            "titleNightColor2": "ff8C55CB",
                            "location": "under"
                        }
                    ]
                },
                "tagPrefix": null,
                "preDepositVO": null,
                "advState": null,
                "subSkuList": null,
                "atmosList": [
                    null,
                    null
                ],
                "jumpUrl": "bilibili://mall/web?url=https%3A%2F%2Fmall.bilibili.com%2Fdetail.html%3Ffrom%3Dshop_search%26loadingShow%3D1%26noTitleBar%3D1%26saleType%3D0%26shopId%3D2233%23noReffer%3Dtrue%26itemsId%3D12305717",
                "jumpUrlH5": "https://mall.bilibili.com/detail.html?from=shop_search&loadingShow=1&noTitleBar=1&saleType=0&shopId=2233#noReffer=true&itemsId=12305717",
                "jumpLinkType": 0,
                "themeId": 0,
                "pubtime": 1745834347,
                "blindRotation": null,
                "living": false,
                "merchantInfo": null,
                "itemAttrs": null,
                "bannerText": "",
                "type": "",
                "interest": "",
                "imageList": null,
                "topSubSku": null,
                "isNewCustom": false,
                "blindCardUrl": ""
            },
            {
                "itemsId": 12480905,
                "bizType": "hyg",
                "itemsType": 1,
                "name": "TAITO AMP＋ VOCALOID 初音未来 Birthday2025 Party ver. 景品手办",
                "price": "119",
                "itemsImg": "https://i0.hdslb.com/bfs/kfptfe/floor/78975410bc17fde3326a0d6914ee868b89e2152d.png",
                "actMaterial": {
                    "cardBgImg": "",
                    "rightIconImg": "//i0.hdslb.com/bfs/mall/mall/54/72/547257984e503749b98f9751b4af7276.png"
                },
                "selfSold": true,
                "tag": "0_3",
                "marketingTag": "",
                "recommendTag": "",
                "soldOut": "0",
                "like": 4107,
                "brief": "",
                "properties": "",
                "preDepositPrice": "0",
                "maxPreDepositPrice": "0",
                "saleType": 0,
                "payType": 0,
                "coin": "",
                "pricePrefix": "",
                "priceSymbol": "¥",
                "priceDesc": [
                    "119"
                ],
                "extraInfo": "{\"TrackId\":\"pbaes.JdyPQyFqiZnSNPqm3nAj2rLMxWdTXTJyHn3x7MptPdluSFNFBD3rRtf_zMVXzK6zyIEvoPEPFC8denGOqgoF3ZaqWaTrT_ixAjDAmyjAZy-mRef3veQWpvejhA6u70I3oAKtnukV-7J_-S9-KDWTIomHW-jAF1-2qrbkAvZWe3s\"}",
                "ipRightName": "",
                "ipRightId": 0,
                "brandName": "",
                "brandId": 0,
                "presaleDeliveryTimeStr": null,
                "preSale": null,
                "remain": null,
                "presaleStartOrderTime": null,
                "tags": {
                    "promotionTagV2": null,
                    "promotionTagNames": null,
                    "marketingTagNames": [
                        "欧气宝箱",
                        "满额权益"
                    ],
                    "saleTypeTagNames": [],
                    "typeAndLimitTagName": "预售",
                    "itemTagNames": [],
                    "recommendTagNames": null,
                    "attributeTagNames": [
                        "新品"
                    ],
                    "rankAndSellPointTagNames": null,
                    "blindBoxHideTypeNames": null,
                    "titleTagNames": [
                        "预售"
                    ],
                    "ticketTag": null,
                    "starBoxSalePoints": [],
                    "exclusiveSalePoints": null,
                    "otherSalePoints": [],
                    "serviceTagNames": [
                        "延期无忧"
                    ],
                    "tagsSort": [
                        "adTagNames",
                        "promotionTagV2",
                        "promotionTagNames",
                        "marketingTagNames",
                        "serviceRightsTags",
                        "recommendTagNames",
                        "otherSalePoints",
                        "saleTypeTagNames",
                        "attributeTagNames",
                        "serviceTagNames"
                    ],
                    "adTagNames": [
                        "自营"
                    ],
                    "serviceRightsTags": []
                },
                "feedTag": {
                    "frontTag": [
                        {
                            "tagType": 1,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "预售",
                            "cornerRadius": 0,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "",
                            "backDayColor2": "",
                            "backNightColor1": "",
                            "backNightColor2": "",
                            "titleDayColor1": "ff18191C",
                            "titleDayColor2": "ff18191C",
                            "titleNightColor1": "ffE7E9EB",
                            "titleNightColor2": "ffE7E9EB",
                            "location": "front"
                        }
                    ],
                    "underTag": [
                        {
                            "tagType": 3,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "自营",
                            "cornerRadius": 4,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "ffFF6699",
                            "backDayColor2": "ffFF6699",
                            "backNightColor1": "ffD44E7D",
                            "backNightColor2": "ffD44E7D",
                            "titleDayColor1": "ffFFFFFF",
                            "titleDayColor2": "ffFFFFFF",
                            "titleNightColor1": "ffFFFFFF",
                            "titleNightColor2": "ffFFFFFF",
                            "location": "under"
                        },
                        {
                            "tagType": 3,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "满额权益",
                            "cornerRadius": 4,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "b3FFECF1",
                            "backDayColor2": "b3FFECF1",
                            "backNightColor1": "ff2F1A22",
                            "backNightColor2": "ff2F1A22",
                            "titleDayColor1": "ffFF6699",
                            "titleDayColor2": "ffFF6699",
                            "titleNightColor1": "ffD44E7D",
                            "titleNightColor2": "ffD44E7D",
                            "location": "under"
                        },
                        {
                            "tagType": 3,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "新品",
                            "cornerRadius": 4,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "b3FFF0E3",
                            "backDayColor2": "b3FFF0E3",
                            "backNightColor1": "ff301B10",
                            "backNightColor2": "ff301B10",
                            "titleDayColor1": "ffFF7F24",
                            "titleDayColor2": "ffFF7F24",
                            "titleNightColor1": "ffD66011",
                            "titleNightColor2": "ffD66011",
                            "location": "under"
                        },
                        {
                            "tagType": 3,
                            "backImgUrl": "",
                            "backImgWidth": 0,
                            "backImgHeight": 0,
                            "title": "延期无忧",
                            "cornerRadius": 4,
                            "useBoard": 0,
                            "boardDayColor1": "",
                            "boardDayColor2": "",
                            "boardNightColor1": "",
                            "boardNightColor2": "",
                            "backDayColor1": "66CEE5FF",
                            "backDayColor2": "66CEE5FF",
                            "backNightColor1": "ff172637",
                            "backNightColor2": "ff172637",
                            "titleDayColor1": "ff2D8CFF",
                            "titleDayColor2": "ff2D8CFF",
                            "titleNightColor1": "ff287FE8",
                            "titleNightColor2": "ff287FE8",
                            "location": "under"
                        }
                    ]
                },
                "tagPrefix": null,
                "preDepositVO": null,
                "advState": null,
                "subSkuList": null,
                "atmosList": [
                    null,
                    null
                ],
                "jumpUrl": "bilibili://mall/web?url=https%3A%2F%2Fmall.bilibili.com%2Fdetail.html%3Ffrom%3Dshop_search%26loadingShow%3D1%26noTitleBar%3D1%26saleType%3D0%26shopId%3D2233%23noReffer%3Dtrue%26itemsId%3D12480905",
                "jumpUrlH5": "https://mall.bilibili.com/detail.html?from=shop_search&loadingShow=1&noTitleBar=1&saleType=0&shopId=2233#noReffer=true&itemsId=12480905",
                "jumpLinkType": 0,
                "themeId": 0,
                "pubtime": 1748675777,
                "blindRotation": null,
                "living": false,
                "merchantInfo": null,
                "itemAttrs": null,
                "bannerText": "",
                "type": "",
                "interest": "",
                "imageList": null,
                "topSubSku": null,
                "isNewCustom": false,
                "blindCardUrl": ""
            },
        ],
        "isRecommend": false,
        "recommendList": null,
        "searchFilter": null,
        "seid": "",
        "traceId": "5f8db7c5f6daf9a05949bff863684700",
        "queryId": "17494835450464392",
        "suggestKeyword": null,
        "querySearch": {
            "type": "",
            "title": "",
            "filterList": null
        },
        "attrFilter": {
            "interval": 0,
            "filters": null
        },
        "recPopup": null,
        "mhTabAb": "g3",
        "wordCard": null
    }
}