// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLoginKeyAndUrl() {
  return window['go']['app']['App']['GetLoginKeyAndUrl']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function VerifyLogin(arg1) {
  return window['go']['app']['App']['VerifyLogin'](arg1);
}
