// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScrapyItem(arg1) {
  return window['go']['app']['App']['CreateScrapyItem'](arg1);
}

export function DeleteScrapyItem(arg1) {
  return window['go']['app']['App']['DeleteScrapyItem'](arg1);
}

export function DoneTask(arg1) {
  return window['go']['app']['App']['DoneTask'](arg1);
}

export function GetLoginKeyAndUrl() {
  return window['go']['app']['App']['GetLoginKeyAndUrl']();
}

export function GetNowRunTaskId() {
  return window['go']['app']['App']['GetNowRunTaskId']();
}

export function ListC2CItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['app']['App']['ListC2CItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ReadAllScrapyItems() {
  return window['go']['app']['App']['ReadAllScrapyItems']();
}

export function RemoveErrorItem(arg1, arg2) {
  return window['go']['app']['App']['RemoveErrorItem'](arg1, arg2);
}

export function StartTask(arg1, arg2) {
  return window['go']['app']['App']['StartTask'](arg1, arg2);
}

export function VerifyLogin(arg1) {
  return window['go']['app']['App']['VerifyLogin'](arg1);
}
