// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetLoginKeyAndUrl():Promise<app.LoginInfo>;

export function Greet(arg1:string):Promise<string>;

export function VerifyLogin(arg1:string):Promise<app.VerifyLoginResponse>;
