// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dao} from '../models';
import {app} from '../models';

export function CreateScrapyItem(arg1:dao.ScrapyItem):Promise<number>;

export function DeleteScrapyItem(arg1:number):Promise<void>;

export function DoneTask(arg1:number):Promise<void>;

export function GetLoginKeyAndUrl():Promise<app.LoginInfo>;

export function Greet(arg1:string):Promise<string>;

export function ListC2CItem(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number):Promise<app.C2CItemListVO>;

export function ReadAllScrapyItems():Promise<Array<dao.ScrapyItem>>;

export function StartTask(arg1:number,arg2:string):Promise<void>;

export function VerifyLogin(arg1:string):Promise<app.VerifyLoginResponse>;
